run:
  go: '1.18'
  concurrency: 4
  timeout: 5m
  skip-dirs:
    - "gen"

linters-settings:
  cyclop:
    max-complexity: 14
  funlen:
    lines: -1
    statements: -1

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - cyclop
    - deadcode
    - depguard
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - varcheck
    - dupl
    - errchkjson
    - errname
    - decorder
    - forcetypeassert
    - funlen
    - gocognit
    - gocritic
    - gofmt
    - gosec
    - ifshort
    - maintidx
    - makezero
    - nestif
    - nilnil
    - nlreturn
    - nolintlint
    - prealloc
    - predeclared
    - unconvert
    - whitespace
    - wsl
    - lll
    - gocritic
